### ISSUE TITLE
DaaS and dashboards

### ISSUE THREAD

**Issue by gbrian** [Flightmate/Flightmate-Stream#1]
Hi,

At http://www.travel-aipi.com we want to build specific dashboard to offer to a client. Is it possible to work/connect with a test endpoint? Thanks

Some questions:
"searchTimestamp": "1544519658" -> In seconds, right?

**Comment by ogelami** [comment]
Hi, unfortunately the Flightmate-Stream is private, if you would like to make a proposition you can write to me at robin@flygresor.se.

correct, searchTimestamp is unix timestamp in seconds.
